### ISSUE TITLE
Changes from Minetest

### ISSUE THREAD

**Issue by FamroFexl** [Jeija/spheretest#12]
Are you still aware of what portions of the code you modified from the original minetest source? Also, what version of minetest were these changes integrated into? I noticed some changes in client/shaders, but are you able to inquire on the specific locations of changes, such as where you limited the world size and wrapped it into a torus? Thanks!

**Comment by Jeija** [comment]
Sorry for the late reply... Anway, you could just filter the commits in this repository by author: https://github.com/Jeija/spheretest/commits/master?author=Jeija

Then just have a look at all the commits that I made starting May 17, 2016. These are all the changes that I made.

**Comment by FamroFexl** [comment]
Thank you!
