### ISSUE TITLE
Update to latest version of minetest to support "mapgen_limit"

### ISSUE THREAD

**Issue by nobodywasishere** [Jeija/spheretest#5]
In the current version of minetest, there is a new value added to limit the size of worlds, configurable by the variable "mapgen_limit". Updating and using this could fix some of the issues arising over the world seam.

**Comment by LunaSquee** [comment]
I'm also wondering if this project will ever be updated as I really like it. It would appear to be abandoned.

**Comment by Jeija** [comment]
Unfortunately I just don't have the time to keep this updated with the latest minetest version. I'd be happy to see this adopted in upstream minetest though at some point. Please also take a look at https://github.com/Jeija/spheretest/issues/4 for some recommendations on how to get this compiling with the current minetest codebase if you'd like to update this project.

**Comment by LunaSquee** [comment]
I understand. Thank you for your quick response!
