### ISSUE TITLE
Making this into a mod?

### ISSUE THREAD

**Issue by nobodywasishere** [Jeija/spheretest#6]
What steps would need to be taken to make this into a mod or subgame? I would love to try my hands at it but I am completely new at github and minetest, though I am learning and I do have a little experience in programming.

**Comment by Jeija** [comment]
If it had been possible to implement this as a mod, I would have done that. Unfortunately it is currently impossible since spheretest basically consists of shaders and C++ code modifications, which both cannot be included in a normal minetest mod.
